### PR TITLE
Add dac_override capability for snapperd_t domain BZ(1619356)

### PR DESCRIPTION
**Pull request by dustymabe**

### CODE REVIEW

**Comment by dustymabe** [comment]
I opened this PR because this looks like the right answer, but please someone who knows the security implications of this tell me if this is the wrong thing to do.

**Comment by wrabcak** [comment]
LGTM.

**Comment by wrabcak** [comment]
Merged. 

Thanks.

**Comment by dustymabe** [comment]
> Merged.

Thank you!

> 
> Thanks.

No Problem

**Pull request merged**
