### PR TITLE
Allow fail2ban execute journalctl BZ(1689034)

### PR DESCRIPTION
**Pull request by zpytela**

### CODE REVIEW

**Comment by wrabcak** [comment]
Hi, 
Thanks for PR. 
How is https://github.com/fedora-selinux/selinux-policy-contrib/pull/91/commits/85031431d7710a24da8eb5ec31a08555663c9c07 related to https://github.com/fedora-selinux/selinux-policy-contrib/pull/91/commits/bd26b7d18488e3e3ff633d28112d5a731f1dc7b6 ?

**Comment by zpytela** [comment]
This branch was by mistake created off non-master branch.

**Comment by zpytela** [comment]
Fedoras 30, 29, and 28 are affected.

Scratchbuild finished, selinux-policy-3.14.4-3.bz1689034.200.fc31 created.
(rpm -qa "selinux-policy*"; sesearch -A -s fail2ban_t -t journalctl_exec_t -c file -p execute,execute_no_trans,getattr,open,read,map; sesearch -A -s fail2ban_t -t fail2ban_t -c capability -p sys_resource; sesearch -A -s fail2ban_t -t fail2ban_t -c process -p setrlimit)
before:
selinux-policy-3.14.4-3.fc31.noarch
selinux-policy-targeted-3.14.4-3.fc31.noarch
selinux-policy-devel-3.14.4-3.fc31.noarch
selinux-policy-doc-3.14.4-3.fc31.noarch
allow domain file_type:file map; [ domain_can_mmap_files ]:True
after:
selinux-policy-3.14.4-3.bz1689034.200.fc31.noarch
selinux-policy-devel-3.14.4-3.bz1689034.200.fc31.noarch
selinux-policy-targeted-3.14.4-3.bz1689034.200.fc31.noarch
selinux-policy-doc-3.14.4-3.bz1689034.200.fc31.noarch
allow domain file_type:file map; [ domain_can_mmap_files ]:True
allow fail2ban_t journalctl_exec_t:file { execute execute_no_trans getattr ioctl lock map open read };
allow fail2ban_t fail2ban_t:capability { dac_read_search sys_resource sys_tty_config };
allow fail2ban_t fail2ban_t:process { fork getcap getpgid getsched setrlimit setsched sigchld sigkill signal signull sigstop };

**Comment by ghost** [comment]
I would probably enclose the sys_resource and setrlimit perms in the optional_policy block as these permissions are specific to journalctl, if you for some reason decide to disable the journalctl policy then these permissions are not needed.

**Comment by zpytela** [comment]
Done. The package with the updated patch has been rebuilt successfully.

**Comment by wrabcak** [comment]
LGTM. Thanks.

**Pull request merged**
