### PR TITLE
Allow pcp_pmie_t domain to use sys_ptrace usernamespace cap

### PR DESCRIPTION
**Pull request by zpytela**

### CODE REVIEW

**Comment by zpytela** [comment]
Rawhide, Fedora 30 and 29 are affected.

**Comment by lberk** [comment]
LGTM

We've been carrying around a patch like this in upstream PCP for some time now, however it's conditional due to not being available in every distro.  Having the rule upstream will definitely simplify PCP's upstream policy a bit, thanks!

**Comment by wrabcak** [comment]
@lberk  Thanks for review! :) 

@zpytela, 
PR branch conflicts with the master, could you please take a look and fix it? 

Thanks,
Lukas.

**Comment by zpytela** [comment]
Hope it is in a better shape now, @wrabcak

**Comment by wrabcak** [comment]
LGTM. THanks.

**Pull request merged**
