### PR TITLE
Remove the ejabberd policies.

### PR DESCRIPTION
**Pull request by bowlofeggs**
The ejabberd policies are now packaged by the ejabberd spec file,
as of the following commit:

https://src.fedoraproject.org/rpms/ejabberd/c/e9cdddd835473981e90316f35ac24247215d6313?branch=master

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by wrabcak** [comment]
Hi @bowlofeggs ,
Sorry for really late reply. I tried package in fedora "ejabberd-selinux". It working well, however you could use our selinux-policy rpm macros to have spec file more clear. More info here[1]

There is also just one interface inside the ejabberd.if file, so we could remove it from Distribution policy. But we need to agreed that I'll remove it from selinux-policy and you'll add dependency in ejabberd-selinux package to require version of selinux-policy without the ejabberd policy.

[1] https://fedoraproject.org/wiki/SELinux/IndependentPolicy

**Comment by bowlofeggs** [comment]
Hello @wrabcak!

Sorry for the long time to reply - I've been away on vacation for a long time.

I hadn't read that page before, so thanks for referencing it for me. I've been keeping the ejabberd policy in the same git repo as the spec file, so I tried to adapt for that. I made a pull request to have ejabberd use some of those macros here:

https://src.fedoraproject.org/rpms/ejabberd/pull-request/4

How does that look to you? As for coordinating a release, all we'd need to do is get the ```selinux_policyver``` global in my patch set to the correct version and we should be good to go. Are you a proven packager? If so, feel free to do it yourself if you like. If not, I should be available to do it this week except for Friday, if you like.

**Comment by bowlofeggs** [comment]
Hello @wrabcak!

What do you think of the changes I referenced above?

**Comment by wrabcak** [comment]
LGTM. 

Could you create copr repository with ejabberd-selinux rpm package to test it? 

We could release with higher priority than 100 (which is handled in selinux-policy rpm macros) and then I'll remove it from distro policy.

**Comment by bowlofeggs** [comment]
@wrabcak I've created a copr here: https://copr.fedorainfracloud.org/coprs/bowlofeggs/ejabberd-selinux/

**Comment by wrabcak** [comment]
@bowlofeggs 
Thanks for that. 

I have few comments:
1.  During process of instalation of ejabberd package I saw:
```
Running scriptlet: ejabberd-18.06-3.fc30.noarch                                                135/136 
Generating SSL certificate /etc/ejabberd/ejabberd.pem...
libsemanage.semanage_direct_install_info: Overriding ejabberd module at lower priority 100 with module at priority 200.
```
This could be redirected to /dev/null 

2. Why you are installing selinux policy for ejabberd in ejabberd rpm package instead of ejabberd-selinux package?

**Comment by bowlofeggs** [comment]
Hello @wrabcak,

Hmmm, I don't see any of those messages when I install on Rawhide:

```
$ sudo dnf install /home/bowlofeggs/rpmbuild/RPMS/noarch/ejabberd-18.06-3.fc30.noarch.rpm /home/bowlofeggs/rpmbuild/RPMS/noarch/ejabberd-selinux-18.06-3.fc30.noarch.rpm
Last metadata expiration check: 0:18:01 ago on Sat 15 Sep 2018 06:48:00 PM EDT.
Dependencies resolved.
======================================================================================================================
 Package                        Arch                 Version                         Repository                  Size
======================================================================================================================
Installing:
 ejabberd                       noarch               18.06-3.fc30                    @commandline               5.5 M
 ejabberd-selinux               noarch               18.06-3.fc30                    @commandline                20 k
Installing dependencies:
 erlang-os_mon                  x86_64               20.3.8.8-1.fc30                 rawhide                    107 k
 erlang-otp_mibs                x86_64               20.3.8.8-1.fc30                 rawhide                     26 k
 logrotate                      x86_64               3.14.0-4.fc29                   rawhide                     68 k

Transaction Summary
======================================================================================================================
Install  5 Packages

Total size: 5.8 M
Total download size: 201 k
Installed size: 9.8 M
Is this ok [y/N]: y
Downloading Packages:
(1/3): erlang-otp_mibs-20.3.8.8-1.fc30.x86_64.rpm                                      22 kB/s |  26 kB     00:01
(2/3): logrotate-3.14.0-4.fc29.x86_64.rpm                                              55 kB/s |  68 kB     00:01
(3/3): erlang-os_mon-20.3.8.8-1.fc30.x86_64.rpm                                        86 kB/s | 107 kB     00:01
----------------------------------------------------------------------------------------------------------------------
Total                                                                                  81 kB/s | 201 kB     00:02
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                              1/1
  Installing       : ejabberd-selinux-18.06-3.fc30.noarch                                                         1/5
  Running scriptlet: logrotate-3.14.0-4.fc29.x86_64                                                               2/5
  Installing       : logrotate-3.14.0-4.fc29.x86_64                                                               2/5
  Installing       : erlang-otp_mibs-20.3.8.8-1.fc30.x86_64                                                       3/5
  Installing       : erlang-os_mon-20.3.8.8-1.fc30.x86_64                                                         4/5
  Running scriptlet: ejabberd-18.06-3.fc30.noarch                                                                 5/5
  Installing       : ejabberd-18.06-3.fc30.noarch                                                                 5/5
  Running scriptlet: ejabberd-18.06-3.fc30.noarch                                                                 5/5
  Verifying        : erlang-os_mon-20.3.8.8-1.fc30.x86_64                                                         1/5
  Verifying        : erlang-otp_mibs-20.3.8.8-1.fc30.x86_64                                                       2/5
  Verifying        : logrotate-3.14.0-4.fc29.x86_64                                                               3/5
  Verifying        : ejabberd-18.06-3.fc30.noarch                                                                 4/5
  Verifying        : ejabberd-selinux-18.06-3.fc30.noarch                                                         5/5

Installed:
  ejabberd-18.06-3.fc30.noarch            ejabberd-selinux-18.06-3.fc30.noarch  erlang-os_mon-20.3.8.8-1.fc30.x86_64
  erlang-otp_mibs-20.3.8.8-1.fc30.x86_64  logrotate-3.14.0-4.fc29.x86_64

Complete!
```

As for the second point, I think I just didn't think much about it - I'll adjust that and make a new build.

**Comment by bowlofeggs** [comment]
```
git diff
diff --git a/ejabberd.spec b/ejabberd.spec
index b9324ba..6216a06 100644
--- a/ejabberd.spec
+++ b/ejabberd.spec
@@ -306,6 +306,8 @@ if [ $1 -gt 1 ]; then
     fi
 fi
 
+
+%pre selinux
 %selinux_relabel_pre -s %{selinuxtype}
 
 
@@ -333,10 +335,12 @@ chown ejabberd:ejabberd ejabberd.pem
 chmod 600 ejabberd.pem
 fi)
 
+
+%post selinux
 %selinux_modules_install -s %{selinuxtype} %{_datadir}/selinux/packages/%{modulename}.pp.bz2
 
 
-%posttrans
+%posttrans selinux
 /usr/sbin/restorecon -i -R /var/lib/ejabberd/
 /usr/sbin/restorecon -i -R /var/log/ejabberd/
 %selinux_relabel_post -s %{selinuxtype}
@@ -349,6 +353,8 @@ fi)
 %postun
 %systemd_postun_with_restart %{name}.service
 
+
+%postun selinux
 if [ $1 -eq 0 ]; then
     %selinux_modules_uninstall -s %{selinuxtype} %{modulename}
 fi
```

I've applied that patch to my [spec file](https://src.fedoraproject.org/rpms/ejabberd/pull-request/4) and it is building in Copr now (same NVR).

BTW, would you care to move over to https://src.fedoraproject.org/rpms/ejabberd/pull-request/4 to review this change rather than here? Might be easier to leave comments.

**Comment by bowlofeggs** [comment]
Hello @wrabcak!

How does this look? Are you ready to merge and coordinate a release?

**Comment by bowlofeggs** [comment]
Greetings! Can we get this done soon? It's been open for a pretty long time.

**Comment by wrabcak** [comment]
Hi yes, 
Let's remove it from rawhide. I'll create new selinux-policy rpm package without ejabberd policy. Right?

**Comment by bowlofeggs** [comment]
Thanks @wrabcak!

You had mentioned that we needed to coordinate the ```selinux_policyver``` variable. I currently have it set to [3.14.2](https://src.fedoraproject.org/rpms/ejabberd/blob/f0e0ee4f685c055397109b589d7e9a2772916904/f/ejabberd.spec#_26) in my spec file. What value should I put there?

**Comment by wrabcak** [comment]
@bowlofeggs,
You already shipping ejabberd-selinux package so there should be no need to coordinate.

**Pull request merged**
