### PR TITLE
[WIP] Allow named_t bind a generic port BZ(1667742)

### PR DESCRIPTION
**Pull request by zpytela**
Signed-off-by: Zdenek Pytela <zpytela@redhat.com>

### CODE REVIEW

**Comment by zpytela** [comment]
This patch changes

	allow $1 ephemeral_port_type:udp_socket name_bind;
to
	allow $1 { port_t unreserved_port_t ephemeral_port_t }:udp_socket name_bind;
	dontaudit $1 defined_port_type:udp_socket name_bind;

so not completely sure if it can be considered an expected result.

**Comment by ghost** [comment]
I find it strange that all these bug reports only apply to port 61000. There was a recent change to the ephemeral port range which removed 61000 ffrom it.

1. Why does unbound use 61000?

# cat /proc/sys/net/ipv4/ip_local_port_range
32768   60999

I would probably ask around a little about this issue before appying the big hammer

**Comment by wrabcak** [comment]
Agree with @doverride  here. Let's keep it open here and bring unbound people to the discussion.

**Comment by zpytela** [comment]
It is likely related to resolving the following bz:
https://bugzilla.redhat.com/show_bug.cgi?id=1518807

Need to get in touch with unbound devels.

**Comment by wrabcak** [comment]
I don't know how that bug is related to this one.

**Comment by zpytela** [comment]
Before applying bz 1518807, 61000/udp had the ephemeral_port_t label, now it gets port_t.
While named_t is allowed name_bind to udp_socket with ephemeral_port_t, it is not for port_t.
```
  # sesearch -A -s named_t -c udp_socket -p name_bind
allow named_t bgp_port_t:udp_socket name_bind;
allow named_t dhcpc_port_t:udp_socket name_bind;
allow named_t dns_port_t:udp_socket { name_bind recv_msg send_msg };
allow named_t ephemeral_port_type:udp_socket name_bind;
allow named_t flash_port_t:udp_socket name_bind;
allow named_t ipp_port_t:udp_socket name_bind;
allow named_t kerberos_port_t:udp_socket name_bind;
allow named_t rtsp_port_t:udp_socket name_bind;
allow named_t unreserved_port_type:udp_socket name_bind;
allow named_t whois_port_t:udp_socket name_bind;
allow nsswitch_domain ephemeral_port_t:udp_socket name_bind; [ nis_enabled ]:True
allow nsswitch_domain port_t:udp_socket name_bind; [ nis_enabled ]:True
allow nsswitch_domain unreserved_port_t:udp_socket name_bind; [ nis_enabled ]:True
```

**Comment by zpytela** [comment]
Closing, resolved by a settings change in unbound.

**Pull request closed without merging**
