### PR TITLE
Allow zabbix_t domain to manage zabbix_var_lib_t sock files and connect to unix_stream_socket

### PR DESCRIPTION
**Pull request by 5umm3r15**
Added rules for Zabbix - software that monitors numerous parameters of a network and the health and integrity of servers.

### CODE REVIEW

**Comment by wrabcak** [comment]
@5umm3r15  Could you please add reference to the Red Hat bugzilla? 

Thanks,
Lukas.

**Comment by 5umm3r15** [comment]
Fixed Red Hat Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1683820

**Comment by wrabcak** [comment]
LGTM.

**Comment by wrabcak** [comment]
LGTM.

**Pull request merged**
