### PR TITLE
Allow init start freenx-server

### PR DESCRIPTION
**Pull request by zpytela**

### CODE REVIEW

**Comment by zpytela** [comment]
The package builds and installs, the service starts.
```
# sesearch -A -s init_t -t nx_server_t -c process -p transition; sesearch -T -s init_t -t nx_server_exec_t -c process
allow initrc_domain daemon:process transition;
type_transition init_t nx_server_exec_t:process nx_server_t;
```
Please review.

**Comment by WOnder93** [comment]
@zpytela BTW, you can mark code blocks (i.e. also shell commands and their output) on GitHub like this:

\```
\# rm -rf /
\```
becomes:
```
# rm -rf /
```
It is more readable and you avoid unwanted formatting triggered by special characters.

**Comment by zpytela** [comment]
@WOnder93 thx, fixed

**Comment by wrabcak** [comment]
LGTM.

Thanks,
Lukas.

**Pull request merged**
