### PR TITLE
Allow openvswitch netlink_audit_socket permissions

### PR DESCRIPTION
**Pull request by lhh**
https://bugzilla.redhat.com/show_bug.cgi?id=1500122

Signed-off-by: Lon Hohberger <lhh@redhat.com>

### CODE REVIEW

**Review by lhh — COMMENTED** [review]
Note: I didn't see any macros in selinux-policy that allowed create and nlmsg_relay.

**Comment by apevec** [comment]
Few more rules are needed, see https://bugzilla.redhat.com/show_bug.cgi?id=1498797#c5 and later comments.

**Comment by lhh** [comment]
That's true, I'll update it Monday. The new changes were tested.

**Comment by lhh** [comment]
Actually, this is superseded by PR# 33. Closing.

**Pull request closed without merging**
