### PR TITLE
Allow sssd read systemd-resolved runtime directory

### PR DESCRIPTION
**Pull request by zpytela**
Resolves: rhbz#1811556

### CODE REVIEW

**Comment by wrabcak** [comment]
Is it connected to this issue? https://github.com/fedora-selinux/selinux-policy-contrib/commit/6ac41c5b089731d9c5509db5ef6eae5944263b20 

If yes, would it make sense to make one macro putting these allow rules together?

**Comment by zpytela** [comment]
If accepted, it should be backported also to F31 and F30.

@wrabcak, I was rather questioning myself if both these permission should be allowed for nsswitch_domain. So far it was only requested for sssd_t though.

**Comment by wrabcak** [comment]
Maybe we should be proactive here and address it before users start reporting bugzilla tickets. 

@lslebodn what is your opinion here?

**Comment by lslebodn** [comment]
I assume rhbz#1811556 is related to reading file /run/systemd/resolve/resolv.conf

```
sh$ semanage fcontext -l | grep systemd_resolved_var_run_t
/run/systemd/resolve(/.*)?                         all files          system_u:object_r:systemd_resolved_var_run_t:s0 
/var/run/systemd/resolve(/.*)?                     all files          system_u:object_r:systemd_resolved_var_run_t:s0
```

and thus it should be allowed just for sssd daemon itself `sssd_t`. It is not related to the client code.

**Comment by zpytela** [comment]
@wrabcak, given the answer I propose the PR for review as is.

**Pull request merged**
