### PR TITLE
Red Hat Bug 1627075 - Create a SELinux boolean to disable cron-logrotate transition

### PR DESCRIPTION
**Pull request by ngutlhtej**
I think this is enough to implement the requested feature in the Bugzilla ticket. Please correct me if I am wrong.

### CODE REVIEW

**Comment by ngutlhtej** [comment]
@wrabcak @milosmalik are both contacts on the BZ ticket: https://bugzilla.redhat.com/show_bug.cgi?id=1627075

Please help me write this feature.

Thank you!

**Comment by wrabcak** [comment]
Hi, 
Could you squash commits to one, it's really chaotic.

**Comment by ngutlhtej** [comment]
> Hi,
> Could you squash commits to one, it's really chaotic.

https://github.com/fedora-selinux/selinux-policy-contrib/pull/88

**Comment by wrabcak** [comment]
We continue in #88

**Pull request closed without merging**
