### PR TITLE
Allow certmonger create directories in a generic certificates directory

### PR DESCRIPTION
**Pull request by zpytela**

### CODE REVIEW

**Comment by WOnder93** [comment]
Expanding on my [comment in #348](https://github.com/fedora-selinux/selinux-policy-contrib/pull/348/files#r514474998), how about just extending `miscfiles_manage_all_certs()` with the `create` permission for `dir`s? (And removing the two new `miscfiles_*_generic_cert_dirs()` interfaces?)

**Comment by zpytela** [comment]
To recap: the current state is
```
allow certmonger_t cert_type:dir { add_name getattr ioctl lock open read remove_name search write };
allow certmonger_t cert_type:file { append create getattr ioctl link lock open read rename setattr unlink write };
```
There is a request for `dir create` and, based on the filename, there will be a rename requested later, too. The only existing superset is the _manage_ interface.

**Comment by zpytela** [comment]
A new PR to modify existing an existing interface reflecting the current state:
https://github.com/fedora-selinux/selinux-policy/pull/468

**Comment by zpytela** [comment]
Closing this PR in favor of https://github.com/fedora-selinux/selinux-policy-contrib/pull/356

**Pull request closed without merging**
